install.packages("renv")


# 03_visualization.R - Coder 3 (Visualization)
# Generates required figures for the NBA project.

# 1. Load necessary libraries
library(tidyverse) # Includes ggplot2 and dplyr
library(here)
library(yaml)     # For reading config.yml

# 2. Read configuration and data
# Ensure config.yml exists and contains the 'team' field
here::i_am("config.yml")
config <- read_yaml(here("config.yml"))
team_filter <- config$team

# Read cleaned data (generated by Coder 5)
data_cleaned <- readRDS(here("results", "01_dataclean.Rds"))

# 3. Apply customization filter (Team filtering logic: ALL or specific team)
if (team_filter != "ALL") {
  # Ensure Team variable is character type
  data_filtered <- data_cleaned %>%
    mutate(Team = as.character(Team)) %>%
    filter(Team == team_filter)
  message(paste("Filtering data for team:", team_filter, ". N =", nrow(data_filtered)))
} else {
  data_filtered <- data_cleaned
  message("Using full dataset (ALL teams). N = ", nrow(data_filtered))
}

# Output director
dir.create(here("results", "03_results"), recursive = TRUE, showWarnings = FALSE)

# 4. Generate REQUIRED FIGURES

# (A) Histogram: Distribution of PTS (results/03_results/hist_pts.png)
hist_pts <- ggplot(data_filtered, aes(x = PTS)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  labs(title = paste("Distribution of Points Per 36 Minutes", ifelse(team_filter != "ALL", paste0(" (", team_filter, ")"), "")),
       x = "Points Per 36 Minutes (PTS)",
       y = "Number of Players") +
  theme_minimal(base_size = 14)

ggsave(here("results", "03_results", "hist_pts.png"), hist_pts, width = 8, height = 5)


# (B) Boxplot: Comparison of PTS by position (Pos) (results/03_results/box_pts_position.png)
# Simplify position labels to Guard, Forward, Center for comparison
box_data <- data_filtered %>%
  mutate(
    Position_Simple = str_extract(Pos, "[A-Z]"),
    Position_Category = case_when(
      Position_Simple == "G" ~ "Guard",
      Position_Simple == "F" ~ "Forward",
      Position_Simple == "C" ~ "Center",
      TRUE ~ "Other" # Exclude unclassified positions
    )
  ) %>%
  filter(Position_Category != "Other")

box_pts_position <- ggplot(box_data, aes(x = Position_Category, y = PTS, fill = Position_Category)) +
  geom_boxplot(alpha = 0.7) +
  labs(title = paste("PTS Distribution by Player Position", ifelse(team_filter != "ALL", paste0(" (", team_filter, ")"), "")),
       x = "Position",
       y = "Points Per 36 Minutes (PTS)") +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

ggsave(here("results", "03_results", "box_pts_position.png"), box_pts_position, width = 8, height = 5)


# (C) Bar chart: Top 10 players by PTS (results/03_results/top10_pts_bar.png)
# Note: If the filtered team has fewer than 10 players, it displays all of them
top_players <- data_filtered %>%
  arrange(desc(PTS)) %>%
  slice_head(n = 10) %>%
  # Create labels for the chart
  mutate(Player_Team = paste0(Player, " (", Team, ")"),
         Player_Team = fct_reorder(Player_Team, PTS))

bar_top10 <- ggplot(top_players, aes(x = Player_Team, y = PTS, fill = Team)) +
  geom_col() +
  coord_flip() + # Flip coordinates for better readability
  labs(title = paste("Top", nrow(top_players), ifelse(team_filter != "ALL", paste0(" ", team_filter, " Players by PTS"), " NBA Players by PTS")),
       subtitle = "Based on per-36 minute statistics",
       x = "Player (Team)",
       y = "Points Per 36 Minutes (PTS)") +
  theme_minimal(base_size = 14) +
  # Hide legend if ALL teams are shown
  {if (team_filter == "ALL") theme(legend.position = "none")}

ggsave(here("results", "03_results", "top10_pts_bar.png"), bar_top10, width = 8, height = 6)


# (D) Scatterplot: MP vs PTS, colored by Team (results/03_results/scatter_mp_pts.png)
scatter_mp_pts <- ggplot(data_filtered, aes(x = MP, y = PTS, color = Team)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "darkred", linetype = "dashed") + # Add trendline
  labs(title = paste("Minutes Played vs. Points Per 36 Minutes", ifelse(team_filter != "ALL", paste0(" (", team_filter, ")"), "")),
       x = "Minutes Played Per 36 Minutes (MP)",
       y = "Points Per 36 Minutes (PTS)",
       color = "Team") +
  theme_minimal(base_size = 14) +
  # Hide legend if ALL teams are shown to avoid clutter
  {if (team_filter == "ALL") theme(legend.position = "none")}

ggsave(here("results", "03_results", "scatter_mp_pts.png"), scatter_mp_pts, width = 8, height = 6)

message("Visualization script 03_visualization.R completed.")
message("Figures saved to results/03_results/.")